spring:
  application:
    name: hystrix-turbine
server:
  port: 6002

turbine:
  app-config: request  # 指定需要收集监控信息的服务名，多个服务用英文下的逗号分隔
  cluster-name-expression: "'default'" #指定集群名称，默认表达式appName
  combine-host-port: true  
    
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10 # 客户端向注册中心发送心跳的时间间隔 默认值30
    lease-expiration-duration-in-seconds: 120 # 租期到期时间，也就是注册中心收到客户端最后一次心跳的间隔时间，如果超过则服务下线 默认值 90
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka/ # 一个
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/ # 多个  