spring:
  application:
    name: config-server # 名称 
  cloud:
    config:
      server:
        git:
          uri: file://Users/yangdd/Documents/code/GitHub/config-repo # 使用本地仓库（用于测试），格式为：file://${user.home}/config-repo 如果是 Windows 则是 file:///${user.home}/config-repo
          #uri: https://github.com/spring-cloud-samples/config-repo/
          #username: 用户名
          #password: 密码
          default-label: config # 可以是 commit id，branch name, tag name，默认值为 master
          #search-paths: # 表示除了在根目录搜索配置文件，还可以在一下目录搜索
          #- user       
    stream:
      kafka: 
        binder:
          zk-nodes: 192.168.222.130:2181
          brokers: 192.168.222.130:9092        
management:
  security:
    enabled: false   
server:
  port: 4001 # 端口   