spring:
  application:
    name: config-server # 名称 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yangdd1205/spring-cloud-master/
          default-label: config
          #search-paths:
          #- 
    
server:
  port: 4001 # 端口   