spring:
  application:
    name: config-server # 名称 
  cloud:
    config:
      server:
        git:
          uri: file://Users/yangdd/Documents/code/GitHub/config-repo # 使用本地仓库（用于测试），格式为：file://${user.home}/config-repo 如果是 Windows 则是 file:///${user.home}/config-repo
          #uri: https://github.com/spring-cloud-samples/config-repo/
          #username: 用户名
          #password: 密码
          default-label: config # 可以是 commit id，branch name, tag name，默认值为 master
          #search-paths: # 表示除了在根目录搜索配置文件，还可以在一下目录搜索
          #- user          
server:
  port: 4003 # 端口   
  
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10 # 客户端向注册中心发送心跳的时间间隔 默认值30
    lease-expiration-duration-in-seconds: 30 # 租期到期时间，也就是注册中心收到客户端最后一次心跳的间隔时间，如果超过则服务下线 默认值 90
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ # 一个  