spring:
  application:
    name: gateway
server:
  port: 6001
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10 # 客户端向注册中心发送心跳的时间间隔 默认值30
    lease-expiration-duration-in-seconds: 30 # 租期到期时间，也就是注册中心收到客户端最后一次心跳的间隔时间，如果超过则服务下线 默认值 90
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ # 一个
      #defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/ # 多个
zuul:
  routes:
    api-hello:
      path: /hello-service/**
      service-id: hello
    api-hi:
      path: /hi-service/**
      service-id: hi          